package com.attractions.attractionsProject.model;

public enum AttractionType {

    NATURAL, // National parks, mountains, beaches, waterfalls...
    CULTURAL, // Museums, historical sites, art galleries...
    ENTERTAINMENT, // Amusement parks, theaters, concert halls...
    ARCHITECTURAL, // Famous buildings, monuments, bridges...
    WILDLIFE; // Zoos, aquariums, wildlife reserves...

}
