package com.attractions.attractionsProject.model;

public enum ServiceType {

    GUIDED_TOURS, // Walking tours, bus tours, historical and culinary tours...
    MULTIMEDIA_GUIDES, // Audio guide rentals, smartphone apps, interactive kiosks...
    TICKETING, // Standard admission tickets, skip-the-line tickets, multiple attractions tickets...
    TRANSPORTATION, // Shuttle services, public transport, rental services...
    ASSISTANCE, // Tourist information centers, concierge services...
    WORKSHOPS, // Hands-on cultural workshops, local cooking classes, art and craft sessions...
    PHOTOGRAPHY, // Professional photo sessions, guided photography, drone photography...
    ACCESSIBILITY; // Individuals with disabilities assistance, availability of mobility aids...
}
